language: node_js
node_js: 8
script:
- npm run build
deploy:
  provider: npm
  email: bryphe@outlook.com
  skip_cleanup: true
  api_key:
    secure: Y04cqsUZnQhRvarSNPtL/aSrfOs0jjl1zVr/4dPP5rZeHvscFmRcOF52c8mmyCXyty6AR3QGxXuWdp8XrptOLO6lsNmEeZ2Q93DbhqWIUOx1EhoLI+OtrZrT/ZhToqpzJxIJ9+LlBX+uI6l7qNOmyVp6el1O8FRD62GL5TOaHkErwY0bejNHeghSz3T9cve3ukxEpNSFwxgoww7XFh8AFued+T8o3x0fjLI1JQkTI+2n+/OgiE/THkAobeYPjQVLCeSLNzhUuo4s1n1hNCCWVEDcjB1efOwgyd3jTDWrx4ceJvkxQlmUagpVU3UOErwuIKx5zsp4nJXAdtMzzNucmgSIQNrX/1fyydT/YW5pXECvkIxurv41wMqOtnakKfZcjRWAKBbj8xoKQJHvD++sq91BMtm8LuHMwiFKat6qGycCOnTmdpYnBf2yhRiR6vldU8i7MCHkTkc3dzx9F17ORBUndSUkx2cYzgyM6ET8kCCswKlxQY4Fu64HrBHLdlPmK/+ubHqjHzjyMJRzk6F9n6gb3GN5ctZZZ5YIM012ot5h+JrPY7RA4VqP+pSd8clsmoZ9kHGgUrUyhQpt2GQXKCLMP3EZN0AOwWVfPW3vcdJcDm90JlBTPruQ+Kuc/p4yjfWMiLCktfwmMVplYFfYapwK3zlttg7xSEjP/OrgDys=
  on:
    repo: onivim/oni-types
